name: Cypress Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  run-cypress-tests:
    runs-on: ubuntu-latest
    needs: build-static-site
    steps:
      - uses: actions/checkout@v3
      
      # @todo: Cache node modules
      - name: Install Cypress
        run: npm install cypress --save-dev

      - name: Run Cypress tests
        run: npx cypress run

      - name: Upload Cypress artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: cypress/videos
