# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-assets:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        cache: 'npm'

    - name: Install Node.js dependencies
      run: npm ci

    - name: Build assets for development
      run: npm run dev

    - name: Build assets for production
      run: npm run prod

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: 'assets'
        path: 'dist'
