# Split the monorepo into readonly branches
# TODO: Some way to preserve commit messages? I'd love to get some help here. 
#       ✔ Done, though it only gets the latest commit. It would be great to have something that handles all commit messages. Or at least says "<commit msg> (and X more [commits]) Maybe this could be done by creating an auto-closing PR listing all the commits since the last merge? Preferably filtered to only contain changes affecting the package.

name: 🪓 Split monorepo

on:
  push:
    branches: [ "master" ]

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref_type }}-${{ github.ref }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  

  framework: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout hydephp/develop
      uses: actions/checkout@v3
      with:
        path: develop
        persist-credentials: false 

    - name: Checkout hydephp/framework
      uses: actions/checkout@v3
      with:
        repository: hydephp/framework
        path: framework
        ref: develop
        fetch-depth: 0
        persist-credentials: false 
    
    - name: Copy over files
      run: cp -rf develop/packages/framework/. framework -v

    - name: Commit and push changes
      run: |
        cd framework

        git config user.name github-actions
        git config user.email github-actions@github.com
        git remote add upstream https://${{ secrets.PAT }}@github.com/hydephp/framework.git

        git add .
        git commit -m "${{ github.event.head_commit.message }} (https://github.com/hydephp/develop/commit/${{ github.sha }})" || true
        # @TODO add all previous commits to the commit message
        
        git push upstream develop || true


  realtime-compiler: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout hydephp/develop
      uses: actions/checkout@v3
      with:
        path: develop
        persist-credentials: false 

    - name: Checkout hydephp/realtime-compiler
      uses: actions/checkout@v3
      with:
        repository: hydephp/realtime-compiler
        path: realtime-compiler
        ref: develop
        fetch-depth: 0
        persist-credentials: false 
    
    - name: Copy over files
      run: cp -rf develop/packages/realtime-compiler/. realtime-compiler -v

    - name: Commit and push changes
      run: |
        cd realtime-compiler

        git config user.name github-actions
        git config user.email github-actions@github.com
        git remote add upstream https://${{ secrets.PAT }}@github.com/hydephp/realtime-compiler.git

        git add .
        git commit -m "${{ github.event.head_commit.message }} (https://github.com/hydephp/develop/commit/${{ github.sha }})" || true
        # @TODO add all previous commits to the commit message
        
        git push upstream develop || true


  hydefront: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout hydephp/develop
      uses: actions/checkout@v3
      with:
        path: develop
        persist-credentials: false 

    - name: Checkout hydephp/hydefront
      uses: actions/checkout@v3
      with:
        repository: hydephp/hydefront
        path: hydefront
        ref: develop
        fetch-depth: 0
        persist-credentials: false 
    
    - name: Copy over files
      run: cp -rf develop/packages/hydefront/. hydefront -v

    - name: Commit and push changes
      run: |
        cd hydefront

        git config user.name github-actions
        git config user.email github-actions@github.com
        git remote add upstream https://${{ secrets.PAT }}@github.com/hydephp/hydefront.git

        git add .
        git commit -m "${{ github.event.head_commit.message }} (https://github.com/hydephp/develop/commit/${{ github.sha }})" || true
        # @TODO add all previous commits to the commit message
        
        git push upstream develop || true



  hyde: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout hydephp/develop
      uses: actions/checkout@v3
      with:
        path: develop
        persist-credentials: false 

    - name: Checkout hydephp/hyde
      uses: actions/checkout@v3
      with:
        repository: hydephp/hyde
        path: hyde
        ref: develop
        fetch-depth: 0
        persist-credentials: false 

    - name: Download base files
      run: wget https://github.com/hydephp/develop/zipball/${{ github.sha }} -O hyde.zip
      
    - name: Unzip archive
      run: unzip hyde.zip

    - name: Empty the hyde directory
      run: rm -rf hyde/* 

    - name: Copy over base files
      run: cp -rf hydephp-develop-*/* hyde -v
 
    - name: Copy over persisted files
      run: cp -rf develop/packages/hyde/. hyde -v

    - name: Commit and push changes
      run: |
        cd hyde

        git config user.name github-actions
        git config user.email github-actions@github.com
        git remote add upstream https://${{ secrets.PAT }}@github.com/hydephp/hyde.git

        git add .
        git commit -m "${{ github.event.head_commit.message }} (https://github.com/hydephp/develop/commit/${{ github.sha }})" || true
        # @TODO add all previous commits to the commit message
        
        git push upstream develop || true
