# Split the monorepo into readonly branches
# TODO: Some way to preserve commit messages? I'd love to get some help here.

name: Split monorepo

on:
  push:
    branches: [ "master" ]

jobs:
  
  package-framework:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Package Hyde/Framework artifact
      uses: actions/upload-artifact@v1
      with:
        name: "framework"
        path: "packages/framework"

  package-hyde:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Package Hyde/Hyde artifact
      uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 #v3.1.0 
      with:
        name: "hyde"
        path: | # Exclude directories covered by export-ignore
          !.github/
          !tests/
          !packages/
          !build/


  propagate-framework:
    needs: package-framework
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
          ref: 'readonly-framework-mirror'

    - name: Empty working directory
      run: rm -rf *

    - name: Download Hyde/Framework artifact
      uses: actions/download-artifact@v3
      with:
        name: framework
        path: '.'

    # Apply transformations if needed

    - name: Commit changes
      uses: EndBug/add-and-commit@v9 

  propagate-hyde:
    needs: package-hyde
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
          ref: 'readonly-hyde-mirror'

    - name: Empty working directory
      run: rm -rf *

    - name: Download Hyde/Hyde artifact
      uses: actions/download-artifact@v3
      with:
        name: hyde
        path: '.'

    # Apply transformations

    - name: Load persisted data
      run: wget https://raw.githubusercontent.com/caendesilva/hyde-monorepo/${{ github.sha }}/build/monorepo/persist/hyde/README.md -O README.md

    - name: Download composer fix script
      run: wget https://gist.githubusercontent.com/caendesilva/8528ef3ab2f5d116c2b58af9ff1c211b/raw/01fcae28cdec1d26b0494331175b301a4e5b2852/fixcomposer.json.php -O fixcomposer.php
    - name: Remove packages from composer.json
      run: php fixcomposer.php
    - name: Remove composer.lock
      run: rm -f composer.lock

    - name: Validate composer.json
      run: composer validate --strict

    - name: Commit changes
      uses: EndBug/add-and-commit@v9