# Split the monorepo into readonly branches
# TODO: Some way to preserve commit messages? I'd love to get some help here. 
#       ✔ Done, though it only gets the latest commit. It would be great to have something that handles all commit messages. Or at least says "<commit msg> (and X more [commits])

name: Split monorepo

on:
  push:
    branches: [ "master" ]

jobs:
  
  package-framework:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Package Hyde/Framework artifact
      uses: actions/upload-artifact@v1
      with:
        name: "framework"
        path: "packages/framework"


  propagate-framework:
    needs: package-framework
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
          ref: 'readonly-framework-mirror'

    - name: Empty working directory
      run: rm -rf *

    - name: Download Hyde/Framework artifact
      uses: actions/download-artifact@v3
      with:
        name: framework
        path: '.'

    # Apply transformations if needed

    - name: Commit changes
      uses: EndBug/add-and-commit@v9 
      with:
        message: ${{ github.event.head_commit.message }}
        
  propagate-hyde:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
          ref: 'readonly-hyde-mirror'

    - name: Empty working directory
      run: rm -rf *

    - name: Create temporary working directory
      run: mkdir ~/tmp

    - name: Download Hyde/Hyde 
      run: cd ~/tmp && wget https://github.com/hydephp/develop/zipball/${{ github.sha }} -O hyde.zip

    - name: Unzip archive
      run: cd ~/tmp && unzip hyde.zip

    - name: Copy archive to root
      run: cp -r ~/tmp/hydephp-develop-*/* .
    
      
    # Apply transformations

    - name: Load persisted data
      run: wget https://raw.githubusercontent.com/hydephp/develop/${{ github.sha }}/build/monorepo/persist/hyde/README.md -O README.md

    - name: Download composer fix script
      run: wget https://gist.githubusercontent.com/caendesilva/8528ef3ab2f5d116c2b58af9ff1c211b/raw/01fcae28cdec1d26b0494331175b301a4e5b2852/fixcomposer.json.php -O fixcomposer.php
    - name: Remove packages from composer.json
      run: php fixcomposer.php
    - name: Delete script
      run: rm fixcomposer.php
    - name: Remove composer.lock
      run: rm -f composer.lock

    - name: Validate composer.json
      run: composer validate --strict

    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        message: ${{ github.event.head_commit.message }}
