name: Test Suite (Matrix)
# @todo download the actual branch from the PR that triggered it instead of requring hyde/framework:dev-master
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # First run tests with coverage. If this fails, we don't need to run the matrix.
  coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
        coverage: xdebug
        extensions: fileinfo
    - name: Install Hyde
      run: git clone https://github.com/hydephp/hyde.git $(pwd)
    - name: Install Dependencies
      run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Set Framework version to dev-master
      run: composer require hyde/framework:dev-master
    - name: Set environment to testing
      run: echo "ENV=testing" > .env
    - name: Run tests with output coverage reporting
      run: vendor/bin/pest --coverage
      env: 
        ENV: testing


  hyde-tests:
    needs: coverage
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
        extensions: fileinfo
    - name: Install Hyde
      run: git clone https://github.com/hydephp/hyde.git $(pwd)
    - name: Install Dependencies
      run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Set Framework version to dev-master
      run: composer require hyde/framework:dev-master
    - name: Set environment to testing
      run: echo "ENV=testing" > .env
    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      run: vendor/bin/pest
      env: 
        ENV: testing