name: Frontend Cypress Tests

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

jobs:

  run-cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3


      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install Composer Dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'npm'

      - name: Install Cypress
        working-directory: 'tests/Cypress'
        run: npm ci

      - name: Start HydeRC server
        run: php hyde serve --host=127.0.0.1 &

      - name: Run Cypress Tests
        run: cd tests/Cypress && npx cypress run

      - name: Upload Cypress Test Media
        uses: actions/upload-artifact@v3
        with:
          name: 'cypress-media'
          path: |
            tests/Cypress/cypress/screenshots
            tests/Cypress/cypress/videos
            