name: Update Hydefront

on:
  push:
    branches: [ master ]

  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  propagate-hydefront:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Enter the resources/frontend directory
      run: cd resources/frontend

    - name: Checkout to a new branch
      run: git checkout -b framework-merge

    - name: Stage the Hydefront files
      run: git add .
    
    - name: Commit the changes
      run: git commit -m "Update Hydefront files from HydePHP/Framework"

    - name: Push the changes to Hydefront
      run: git push origin framework-merge
