name: Update Hydefront

on:
  push:
    branches: [ master ]

  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  propagate-hydefront:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Git config
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Clone Hydefront
      run: |
        cd ~ && git clone https://github.com/hydephp/hydefront/

    - name: Copy Hydefront files
      run: |
        cd resources/frontend && cp -r ./* ~/hydefront/


    - name: Add test file
      run: echo "test" > ~/hydefront/test.txt

    - name: Checkout to a new branch
      run: cd ~/hydefront && git checkout -b framework-merge

    - name: Stage the Hydefront files
      run: cd ~/hydefront && git add .
    
    - name: Check if there are changes
      id: check-for-changes
      run: echo "::set-output name=HAS_CHANGES::$(cd ~/hydefront && git diff --name-only --cached)"
    
    - name: Commit the changes
      #if: ${{ steps.check-for-changes.HAS_CHANGES != '' }}
      run: cd ~/hydefront && git commit -m "Update Hydefront files from HydePHP/Framework"

    - name: Set the remote origin
      run: cd ~/hydefront && git remote set-url origin https://${{ env.GITHUB_ACTOR }}:${{ env.GITHUB_TOKEN }}@github.com/hydephp/hydefront.git

    - name: Push the changes to Hydefront
      #if: ${{ steps.check-for-changes.HAS_CHANGES != '' }}
      run: cd ~/hydefront && git push origin framework-merge

