name: Update Hydefront

on:
  push:
    branches: [ master ]

  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  propagate-hydefront:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Create Pull Request in HydePHP/HydeFront
      uses: paygoc6/action-pull-request-another-repo@v1.0.1
      env:
        API_TOKEN_GITHUB: ${{ secrets.ACTIONS_PAT_GITHUB }}
      with:
        source_folder: 'resources/frontend'
        destination_repo: 'hydephp/hydefront'
        destination_folder: 'folder-name'
        destination_base_branch: 'master'
        destination_head_branch: 'framework-merge'
        user_email: 'git@github.com'
        user_name: 'hydephp'
