name: Update Hydefront

on:
  push:
    branches: [ master ]

  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  propagate-hydefront:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Git config
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Checkout to a new branch
      working-directory: ./resources/frontend
      run: git checkout -b framework-merge

    - name: Add test file
      working-directory: ./resources/frontend
      run: echo "test" > test.txt

    - name: Stage the Hydefront files
      working-directory: ./resources/frontend
      run: git add .
    
    - name: Check if there are changes
      working-directory: ./resources/frontend
      id: check-for-changes
      run: echo "::set-output name=HAS_CHANGES::$(git diff --name-only --cached)"
    
    - name: Commit the changes
      working-directory: ./resources/frontend
      #if: ${{ steps.check-for-changes.HAS_CHANGES != '' }}
      run: git commit -m "Update Hydefront files from HydePHP/Framework"

    - name: Push the changes to Hydefront
      working-directory: ./resources/frontend
      #if: ${{ steps.check-for-changes.HAS_CHANGES != '' }}
      run: git push origin framework-merge

